DROP TABLE IF EXISTS PINYIN;
CREATE TABLE PINYIN (
  PINYIN_ID int(11) NOT NULL AUTO_INCREMENT,
  PINYIN_NAME varchar(127) NOT NULL,
  PINYIN_PINYIN varchar(127) NOT NULL,
  PRIMARY KEY (PINYIN_ID)
)
