INSERT INTO PINYIN (PINYIN_NAME, PINYIN_PINYIN) VALUES ('章', 'zhang');
INSERT INTO PINYIN (PINYIN_NAME, PINYIN_PINYIN) VALUES ('子', 'zi');
INSERT INTO PINYIN (PINYIN_NAME, PINYIN_PINYIN) VALUES ('怡', 'yi');
INSERT INTO PINYIN (PINYIN_NAME, PINYIN_PINYIN) VALUES ('武', 'zhao');